AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyIP:
    Description: My IP address
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Stable Diffusion ec2 security group
      GroupName: stablediffusion
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 #Temporary all access to install requirements
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0 #Temporary all access to install requirements
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP #Temporary all access to install requirements
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 #Temporary all access to install requirements
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0 #Temporary all access to install requirements
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP #Temporary all access to install requirements
      VpcId: vpc-0f464b3c0144dff3b
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0efc43a4067fe9a3e
      InstanceType: t2.micro
      KeyName: viet-key
      SecurityGroupIds:
        - !Ref SecurityGroup
      AvailabilityZone: us-east-2a
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -xe
            sudo dnf install -y python3.12
            python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu126
            sudo git clone https://github.com/vietlnguy/aws-stablediffusion.git
            python3 -m pip install -r requirements.txt
            
            DEVICE_NAME="/dev/xvdf"
            MOUNT_POINT="/mnt/data"
            if ! blkid $DEVICE_NAME; then
              mkfs -t ext4 $DEVICE_NAME
            fi
            mkdir -p $MOUNT_POINT
            mount $DEVICE_NAME $MOUNT_POINT
  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: vol-0cd4e27fd2e7414b1
      Device: /dev/xvdf

Outputs:
  SecurityGroupId:
    Description: The ID of the security group attached to the EC2 instance
    Value: !GetAtt SecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}:SecurityGroupId'
