name: aws-stablediffusion-pipeline
run-name: ${{ github.actor }} is deploying to AWS 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Create stack and generate images
        run: aws cloudformation deploy --template-file cloudformation.yml --region us-east-1 --stack-name stablediffusion --capabilities CAPABILITY_NAMED_IAM --parameter-overrides CivitAiKey=${{ secrets.CIVITAI_KEY }} MyIP=${{ secrets.MY_IP }}
      - name: Wait for image generation
        run: |
          prev_value=$(aws s3 ls s3://vietnguy-sd-output/ --recursive | wc -l)
          while true; do
            current_value=$(aws s3 ls s3://vietnguy-sd-output/ --recursive | wc -l)

            if [ "$current_value" -ne "$prev_value" ]; then
                echo "Finished generating images"
                break
            fi

            sleep 30  # Wait before checking again
          done
      - name: Delete stack
        run: aws cloudformation delete-stack --stack-name stablediffusion